# Generated by Django 3.1.3 on 2020-11-12 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20201112_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemphoto',
            name='created',
        ),
        migrations.AddField(
            model_name='itemphoto',
            name='build_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemphoto',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
