# Generated by Django 3.1.3 on 2020-11-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20201112_1155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemPhoto',
            new_name='Photo',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='item_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photo_name',
            new_name='title',
        ),
    ]
