# Generated by Django 3.1.3 on 2020-11-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20201112_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='photo_file',
        ),
    ]
