# Generated by Django 3.1.3 on 2020-11-15 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_auto_20201112_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_hates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PhotoMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_user', models.CharField(max_length=20)),
                ('message_content', models.TextField(blank=True)),
                ('message_post_date', models.DateTimeField(default=datetime.datetime(2020, 11, 15, 9, 33, 24, 73891, tzinfo=utc))),
                ('message_likes', models.IntegerField(default=0)),
                ('message_hates', models.IntegerField(default=0)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.photo')),
            ],
            options={
                'ordering': ('message_post_date',),
            },
        ),
    ]
