# Generated by Django 3.1.3 on 2020-11-15 10:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_auto_20201115_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomessage',
            name='message_post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 10, 19, 42, 167898, tzinfo=utc)),
        ),
    ]
