# Generated by Django 3.1.3 on 2020-11-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0012_auto_20201115_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomessage',
            name='message_content',
            field=models.TextField(blank=True, verbose_name='留言'),
        ),
    ]
