# Generated by Django 3.1.3 on 2020-11-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0013_auto_20201115_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomessage',
            name='message_post_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='留言日期'),
        ),
        migrations.AlterField(
            model_name='photomessage',
            name='message_user',
            field=models.CharField(max_length=20, verbose_name='使用者'),
        ),
    ]
