# Generated by Django 3.1.3 on 2020-11-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0014_auto_20201115_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photomessage',
            options={'ordering': ('message_create_date',)},
        ),
        migrations.RenameField(
            model_name='photomessage',
            old_name='message_post_date',
            new_name='message_create_date',
        ),
    ]
