# Generated by Django 3.1.3 on 2020-11-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0015_auto_20201115_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomessage',
            name='message_user',
        ),
        migrations.AddField(
            model_name='photomessage',
            name='auth.User',
            field=models.CharField(max_length=20, null=True, verbose_name='使用者'),
        ),
    ]
