# Generated by Django 3.1.3 on 2020-11-15 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0016_auto_20201115_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomessage',
            name='auth.User',
        ),
        migrations.AddField(
            model_name='photomessage',
            name='message_user',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='使用者'),
            preserve_default=False,
        ),
    ]
