# Generated by Django 3.1.3 on 2020-11-19 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0019_auto_20201119_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomessage',
            name='likes_hates_user',
        ),
        migrations.AddField(
            model_name='photo',
            name='likes_hates_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
