# Generated by Django 3.1.3 on 2020-11-19 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0021_auto_20201119_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_photo_likes_hates',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='按讚日期'),
            preserve_default=False,
        ),
    ]
