# Generated by Django 3.1.3 on 2020-11-21 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0023_auto_20201121_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
    ]
