# Generated by Django 3.1.3 on 2020-11-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0025_photo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_photo_likes_hates',
            name='created',
        ),
    ]
