# Generated by Django 3.1.3 on 2020-11-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0027_delete_user_photo_likes_hates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomessage',
            name='user',
        ),
    ]
