# Generated by Django 3.1.3 on 2020-11-21 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0028_remove_photomessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='likes_hates_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
