# Generated by Django 3.1.3 on 2020-11-21 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0029_photo_likes_hates_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='likes_hates_user',
        ),
        # migrations.AlterField(
        #     model_name='photomessage',
        #     name='message_user',
        #     field=models.ForeignKey(blank=True,on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        migrations.CreateModel(
            name='PhotoLikeHate',
            fields=[
                ('id', models.AutoField(blank=True,auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_button', models.BooleanField(blank=True,default=False)),
                ('created', models.DateTimeField(blank=True,auto_now_add=True, verbose_name='評論日期')),
                ('photo', models.ForeignKey(blank=True,on_delete=django.db.models.deletion.CASCADE, to='authorization.photo')),
                ('user', models.ForeignKey(blank=True,on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
