# Generated by Django 3.1.3 on 2020-11-21 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0030_auto_20201121_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photolikehate',
            name='photo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.photo'),
        ),
        migrations.AlterField(
            model_name='photolikehate',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
