# Generated by Django 3.1.3 on 2020-11-21 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0032_auto_20201121_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomessage',
            name='photo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.photo'),
        ),
    ]
