# Generated by Django 3.1.3 on 2020-11-21 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0033_auto_20201121_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photolikehate',
            name='check_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photolikehate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photomessage',
            name='message_user',
            field=models.CharField(max_length=20, verbose_name='使用者'),
        ),
    ]
