# Generated by Django 3.1.3 on 2020-11-22 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0037_auto_20201121_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photolikehate',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photolikehate', to='authorization.photo'),
        ),
    ]
