# Generated by Django 3.1.3 on 2020-11-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0039_hobby_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hobbies',
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
